title: Dave Mateer's Blog
email: davemateer@gmail.com
description: In depth articles on software production
baseurl: "" 
url: "https://davemateer.com" 
twitter_username: dave_mateer
github_username:  djhmateer
twitter:
  username: dave_mateer

# the url structure
permalink: /:year/:month/:day/:title

markdown: kramdown

timezone: Europe/London

repository: djhmateer/djhmateer.github.io

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag # twitter / opengraph
  - jekyll-feed # atom
  - jemoji

emoji:
  src: "https://github.githubassets.com/images/icons/"

defaults:
  -
    scope:
      path: ""
      # ie not for pages
      type: "posts"
    values:
      # the default layout to use if none is specified
      layout: post
      # I don't use the concept of drafts so default to published true
      published: true

exclude: 
 - Gemfile
 - Gemfile.lock 
 - docker-compose.yml


