version: '3'

services:
  jekyll: 
    image: jekyll/jekyll
    container_name: davemateer-com
    command: jekyll serve --force_polling
    ports:
        - 4000:4000
    volumes:
        - ./:/srv/jekyll